# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.11.6"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.6"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.6"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.6"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.6"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "=1.11.6"

[prune]
  go-tests = true
  unused-packages = true
